name: seraj
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.1.1
  appwrite: ^17.1.0 # إذا كنت تريد 12.0.0، اتركها. لو تريد أحدث، ضع ^17.1.0
  shared_preferences: ^2.2.3
  uuid: ^4.3.3
  geolocator: ^11.0.0 # إذا كنت تريد 11.0.0، اتركها. لو تريد أحدث، ضع ^14.0.2
  geocoding: ^3.0.0
  flutter_web_auth_2: ^4.1.0 # **** يجب إضافة هذا السطر مجدداً ****

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: "^0.13.1"

flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon.png"
  min_sdk_android: 21
  remove_alpha_ios: true